### ISSUE TITLE
Couldn't get the valid product image through amazon url

### ISSUE THREAD

**Issue by karthikreddi** [ospfranco/link-preview-js#113]
**Describe the bug**
Couldn't get the product image through amazon url.

**To Reproduce**
Go to 'https://www.amazon.in/Noise-Bluetooth-Truly-Wireless-Earbuds/dp/B09F2VK7FC/?_encoding=UTF8&pd_rd_w=jGYxy&pf_rd_p=ee853eb9-cee5-4961-910b-2f169311a086&pf_rd_r=BADPW5Z8QXFEE5E9SM9J&pd_rd_r=dae04816-b1d3-4dbb-9241-0037760159cb&pd_rd_wg=Su60f&ref_=pd_gw_ci_mcx_mr_hp_atf_m&th=1'

**Expected behavior**
Should get the valid product image. Product images are placed at  class '.a-dynamic-image', and has a attribute 'data-old-hires'.

**Screenshots**
![Screenshot 2022-04-27 at 9 38 24 PM](https://user-images.githubusercontent.com/6865275/165563089-a48762a3-3282-48b7-b315-e2567a9056c2.png)

**Desktop (please complete the following information):**
 - OS: [Macbook PRO]
 - Browser [chrome]

**Comment by ospfranco** [comment]
The library works with OpenGraph tags, if amazon has not placed them in the correct tag, it doesn't matter which class they have.

https://github.com/ospfranco/link-preview-js/blob/main/index.ts#L79

If you really want to try to parse specific classes/selectors you can submit a PR, but at the end of the day, there is nothing wrong, because trying to parse specific sites would take thousands of exceptions.
