### ISSUE TITLE
Cannot read property 'parent' of undefined (react-native)

### ISSUE THREAD

**Issue by bockc** [ospfranco/link-preview-js#53]
**Describe the bug**
Promise is rejected when trying to get the preview of any link. (iOS && Android)

**To Reproduce**
1. `import LinkPreview from 'link-preview-js';`
2. `LinkPreview.getPreview('https://www.google.com').then(data => console.log('preview', data));`

**Expected behavior**
Resolving the promise

**Smartphone (please complete the following information):**
 - Device: iPhone 6S
 - OS: iOS 12.4.1
 - React-Native: 0.61.5
 - link-preview-js: 1.6.0

**Additional context**
```
Unhandled promise rejection TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (parse.js:55)
    at module.exports (parse.js:17)
    at Function.exports.load (static.js:19)
    at parseTextResponse (index.js:112)
    at index.js:58
    at run (es6.promise.js:75)
    at es6.promise.js:92
    at flush (_microtask.js:18)
    at tryCallOne (core.js:37)
    at core.js:123
```

I'm not really sure, but I think the issue comes from `cheerio-without-node-native`.
Do you know if your project runs fine on react-native or does it need some tweaking to work ?

**Comment by bockc** [comment]
After testing stuff a little bit more, I changed the require from `cheerio-without-node-native` to `cheerio`, unfortunately the error still remains.

But I found out that if you try `cheerio.load(body)` when `body` is `undefined`, this is what causes the issue. By simply doing `cheerio.load(body || '')` I managed to get this answer:
```
contentType: "text/html; charset=ISO-8859-1"
description: undefined
favicons: ["https://www.google.com/favicon.ico"]
images: []
mediaType: "website"
siteName: undefined
title: ""
url: "https://www.google.com/"
videos: []
__proto__: Object
```

It's better but there are still issues, I'm missing a few data (description, siteName, title,....)
Will keep you posted if I find a fix, but I would appreciate some feedback on my findings :)

**Comment by ospfranco** [comment]
Let's go by parts:

1. You cannot replace `cheerio-without-node` for `cheerio`, because as the name suggest `cheerio` requires node libraries which are not available on RN.
2. As you can see you can get responses from other sites just fine, I also tested again on the simulator and it's working, this clearly is some limitation on cheerio's side when parsing non valid HTML, which apparently is the case for `https://www.google.com` but other links however are working just fine, unfortunately work on cheerio-without-node has stopped, I might replace it if I find a suitable alternative but this seems like an error on the site page rather than on this library, I will however catch the error, since that doesn't seem to be working atm.
3. The title is being parsed by the following function:

```javascript
const getTitle = function (doc) {
  var title = doc("meta[property='og:title']").attr('content');

  if (!title) {
    title = doc('title').text();
  }

  return title;
};
```

I don't know how other apps/libraries parse it, but this is the way this library does it, what the sites put in those fields it's up to the sites, not me.

Thanks for noticing the bug!

**Comment by ospfranco** [comment]
I've updated/re-written the library in typescript, the error is now correctly being thrown when there is a parsing error, I cannot do anything to fix google.com though, let me know if you have any other question.

**Comment by bockc** [comment]
Just so you know, you can use node libraries in RN by using `rn-nodeify`. Not ideal, but if you got not other choice this is the way to go.

**Comment by bockc** [comment]
Also, I tried with your new version (`2.0.0`) and the error is well caught.

But do you think you could use `rn-nodeify` to make `cheerio` work instead of `cheerio-without-node-native` just like I did ?
This would allow you to do `cheerio.load(body || '')` and ensure we can still get basic informations from the text response, like for instance the site picture etc.

**Comment by ospfranco** [comment]
If you look at the response you got, there are several fields missing, at the same time, this library is not RN only, adding nodeify to it might break stuff for node environments and increase the package size.

So that being said, I don't really see the benefit of doing this, in order to fix a single broken HTML document, google will probably publish a new version in no time and then the change is for nothing, happened with youtube a year ago and problem went away on its own.

**Comment by ospfranco** [comment]
however if you feel strongly about it, you can create a PR, test it and if it is good and review it and potentially merge it.

**Comment by bockc** [comment]
> If you look at the response you got, there are several fields missing, at the same time, this library is not RN only, adding nodeify to it might break stuff for node environments and increase the package size.
> 
> So that being said, I don't really see the benefit of doing this, in order to fix a single broken HTML document, google will probably publish a new version in no time and then the change is for nothing, happened with youtube a year ago and problem went away on its own.

You're right, it was a stupid question.
Great work anyway :)

**Comment by canpoyrazoglu** [comment]
I've literally lost hours, trying to use `google.com` as my example domain, which I've learned that isn't working right now. Maybe a warning about trying with some other domain than `google.com` would be helpful.
